// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(construct_transportFFI)
import construct_transportFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_construct_transport_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_construct_transport_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureConstructTransportInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * One QUIC/HTTP-3 connection to a gateway. Open streams from it; they are
 * multiplexed over the single connection.
 */
public protocol QuicChannelProtocol: AnyObject, Sendable {
    
    /**
     * Diagnostic: live quinn connection stats (tx/rx datagrams, PING frames sent, RTT,
     * close reason). Runs on `RT`, so it also proves the dedicated runtime is responsive.
     * `ping_tx` not growing over time ⇒ keep-alive isn't firing.
     */
    func connectionStats() async throws  -> String
    
    /**
     * Open a gRPC call on `path` (`/package.Service/Method`) with extra request
     * `metadata` headers.
     */
    func openStream(path: String, metadata: [GrpcHeader]) async throws  -> QuicStream
    
}
/**
 * One QUIC/HTTP-3 connection to a gateway. Open streams from it; they are
 * multiplexed over the single connection.
 */
open class QuicChannel: QuicChannelProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_construct_transport_fn_clone_quicchannel(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_construct_transport_fn_free_quicchannel(handle, $0) }
    }

    
    /**
     * Connect to `host:port`, pinning the gateway's `trust_cert` (DER).
     * `server_name` is the TLS SNI and must match the cert SAN.
     */
public static func connect(host: String, port: UInt16, serverName: String, trustCert: Data)async throws  -> QuicChannel  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_construct_transport_fn_constructor_quicchannel_connect(FfiConverterString.lower(host),FfiConverterUInt16.lower(port),FfiConverterString.lower(serverName),FfiConverterData.lower(trustCert)
                )
            },
            pollFunc: ffi_construct_transport_rust_future_poll_u64,
            completeFunc: ffi_construct_transport_rust_future_complete_u64,
            freeFunc: ffi_construct_transport_rust_future_free_u64,
            liftFunc: FfiConverterTypeQuicChannel_lift,
            errorHandler: FfiConverterTypeTransportError_lift
        )
}
    
    /**
     * Like [`connect`](Self::connect) but Salamander-obfuscates every datagram with `psk`
     * (the DPI-evading path). The gateway must apply the same PSK; `psk` is provisioned
     * out-of-band via the veil-ticket mechanism, never hardcoded.
     */
public static func connectObfuscated(host: String, port: UInt16, serverName: String, trustCert: Data, psk: Data)async throws  -> QuicChannel  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_construct_transport_fn_constructor_quicchannel_connect_obfuscated(FfiConverterString.lower(host),FfiConverterUInt16.lower(port),FfiConverterString.lower(serverName),FfiConverterData.lower(trustCert),FfiConverterData.lower(psk)
                )
            },
            pollFunc: ffi_construct_transport_rust_future_poll_u64,
            completeFunc: ffi_construct_transport_rust_future_complete_u64,
            freeFunc: ffi_construct_transport_rust_future_free_u64,
            liftFunc: FfiConverterTypeQuicChannel_lift,
            errorHandler: FfiConverterTypeTransportError_lift
        )
}
    

    
    /**
     * Diagnostic: live quinn connection stats (tx/rx datagrams, PING frames sent, RTT,
     * close reason). Runs on `RT`, so it also proves the dedicated runtime is responsive.
     * `ping_tx` not growing over time ⇒ keep-alive isn't firing.
     */
open func connectionStats()async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_construct_transport_fn_method_quicchannel_connection_stats(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_construct_transport_rust_future_poll_rust_buffer,
            completeFunc: ffi_construct_transport_rust_future_complete_rust_buffer,
            freeFunc: ffi_construct_transport_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypeTransportError_lift
        )
}
    
    /**
     * Open a gRPC call on `path` (`/package.Service/Method`) with extra request
     * `metadata` headers.
     */
open func openStream(path: String, metadata: [GrpcHeader])async throws  -> QuicStream  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_construct_transport_fn_method_quicchannel_open_stream(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(path),FfiConverterSequenceTypeGrpcHeader.lower(metadata)
                )
            },
            pollFunc: ffi_construct_transport_rust_future_poll_u64,
            completeFunc: ffi_construct_transport_rust_future_complete_u64,
            freeFunc: ffi_construct_transport_rust_future_free_u64,
            liftFunc: FfiConverterTypeQuicStream_lift,
            errorHandler: FfiConverterTypeTransportError_lift
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeQuicChannel: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = QuicChannel

    public static func lift(_ handle: UInt64) throws -> QuicChannel {
        return QuicChannel(unsafeFromHandle: handle)
    }

    public static func lower(_ value: QuicChannel) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> QuicChannel {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: QuicChannel, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeQuicChannel_lift(_ handle: UInt64) throws -> QuicChannel {
    return try FfiConverterTypeQuicChannel.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeQuicChannel_lower(_ value: QuicChannel) -> UInt64 {
    return FfiConverterTypeQuicChannel.lower(value)
}






/**
 * One gRPC call. Send and receive halves are independently locked, so a Swift
 * sender task and receiver task run concurrently. Every operation runs on `RT`.
 */
public protocol QuicStreamProtocol: AnyObject, Sendable {
    
    /**
     * Half-close the client send side.
     */
    func finish() async throws 
    
    /**
     * Receive the next complete gRPC message, or `None` at end of stream.
     */
    func recvMessage() async throws  -> Data?
    
    /**
     * Await the response headers; returns the HTTP status code.
     */
    func recvResponse() async throws  -> UInt16
    
    /**
     * Read trailing metadata (e.g. `grpc-status`) after the stream ends.
     */
    func recvTrailers() async throws  -> [GrpcHeader]
    
    /**
     * Send one gRPC message.
     */
    func sendMessage(message: Data) async throws 
    
}
/**
 * One gRPC call. Send and receive halves are independently locked, so a Swift
 * sender task and receiver task run concurrently. Every operation runs on `RT`.
 */
open class QuicStream: QuicStreamProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_construct_transport_fn_clone_quicstream(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_construct_transport_fn_free_quicstream(handle, $0) }
    }

    

    
    /**
     * Half-close the client send side.
     */
open func finish()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_construct_transport_fn_method_quicstream_finish(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_construct_transport_rust_future_poll_void,
            completeFunc: ffi_construct_transport_rust_future_complete_void,
            freeFunc: ffi_construct_transport_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeTransportError_lift
        )
}
    
    /**
     * Receive the next complete gRPC message, or `None` at end of stream.
     */
open func recvMessage()async throws  -> Data?  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_construct_transport_fn_method_quicstream_recv_message(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_construct_transport_rust_future_poll_rust_buffer,
            completeFunc: ffi_construct_transport_rust_future_complete_rust_buffer,
            freeFunc: ffi_construct_transport_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionData.lift,
            errorHandler: FfiConverterTypeTransportError_lift
        )
}
    
    /**
     * Await the response headers; returns the HTTP status code.
     */
open func recvResponse()async throws  -> UInt16  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_construct_transport_fn_method_quicstream_recv_response(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_construct_transport_rust_future_poll_u16,
            completeFunc: ffi_construct_transport_rust_future_complete_u16,
            freeFunc: ffi_construct_transport_rust_future_free_u16,
            liftFunc: FfiConverterUInt16.lift,
            errorHandler: FfiConverterTypeTransportError_lift
        )
}
    
    /**
     * Read trailing metadata (e.g. `grpc-status`) after the stream ends.
     */
open func recvTrailers()async throws  -> [GrpcHeader]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_construct_transport_fn_method_quicstream_recv_trailers(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_construct_transport_rust_future_poll_rust_buffer,
            completeFunc: ffi_construct_transport_rust_future_complete_rust_buffer,
            freeFunc: ffi_construct_transport_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeGrpcHeader.lift,
            errorHandler: FfiConverterTypeTransportError_lift
        )
}
    
    /**
     * Send one gRPC message.
     */
open func sendMessage(message: Data)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_construct_transport_fn_method_quicstream_send_message(
                    self.uniffiCloneHandle(),
                    FfiConverterData.lower(message)
                )
            },
            pollFunc: ffi_construct_transport_rust_future_poll_void,
            completeFunc: ffi_construct_transport_rust_future_complete_void,
            freeFunc: ffi_construct_transport_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeTransportError_lift
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeQuicStream: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = QuicStream

    public static func lift(_ handle: UInt64) throws -> QuicStream {
        return QuicStream(unsafeFromHandle: handle)
    }

    public static func lower(_ value: QuicStream) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> QuicStream {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: QuicStream, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeQuicStream_lift(_ handle: UInt64) throws -> QuicStream {
    return try FfiConverterTypeQuicStream.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeQuicStream_lower(_ value: QuicStream) -> UInt64 {
    return FfiConverterTypeQuicStream.lower(value)
}




/**
 * A request/response header pair (e.g. `authorization`, `grpc-status`).
 * Named `GrpcHeader` (not `Metadata`) to avoid colliding with gRPC-swift's
 * `Metadata` type in the app module.
 */
public struct GrpcHeader: Equatable, Hashable {
    public var key: String
    public var value: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(key: String, value: String) {
        self.key = key
        self.value = value
    }

    
}

#if compiler(>=6)
extension GrpcHeader: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGrpcHeader: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GrpcHeader {
        return
            try GrpcHeader(
                key: FfiConverterString.read(from: &buf), 
                value: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: GrpcHeader, into buf: inout [UInt8]) {
        FfiConverterString.write(value.key, into: &buf)
        FfiConverterString.write(value.value, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGrpcHeader_lift(_ buf: RustBuffer) throws -> GrpcHeader {
    return try FfiConverterTypeGrpcHeader.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGrpcHeader_lower(_ value: GrpcHeader) -> RustBuffer {
    return FfiConverterTypeGrpcHeader.lower(value)
}


/**
 * Error surfaced across the FFI boundary.
 */
public enum TransportError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Transport(String
    )

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension TransportError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTransportError: FfiConverterRustBuffer {
    typealias SwiftType = TransportError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TransportError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Transport(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TransportError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Transport(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTransportError_lift(_ buf: RustBuffer) throws -> TransportError {
    return try FfiConverterTypeTransportError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTransportError_lower(_ value: TransportError) -> RustBuffer {
    return FfiConverterTypeTransportError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeGrpcHeader: FfiConverterRustBuffer {
    typealias SwiftType = [GrpcHeader]

    public static func write(_ value: [GrpcHeader], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeGrpcHeader.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [GrpcHeader] {
        let len: Int32 = try readInt(&buf)
        var seq = [GrpcHeader]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeGrpcHeader.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureConstructTransportInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
/**
 * Build/behaviour marker so the iOS app log can confirm exactly which transport binary
 * (.a) is actually linked — Xcode silently reuses a cached static lib, which has masked
 * several fixes. Bump on changes that need on-device verification.
 */
public func transportBuildMarker() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_construct_transport_fn_func_transport_build_marker($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_construct_transport_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_construct_transport_checksum_func_transport_build_marker() != 44196) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_transport_checksum_method_quicchannel_connection_stats() != 26635) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_transport_checksum_method_quicchannel_open_stream() != 8948) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_transport_checksum_method_quicstream_finish() != 54911) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_transport_checksum_method_quicstream_recv_message() != 14555) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_transport_checksum_method_quicstream_recv_response() != 25388) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_transport_checksum_method_quicstream_recv_trailers() != 49466) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_transport_checksum_method_quicstream_send_message() != 27480) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_transport_checksum_constructor_quicchannel_connect() != 1531) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_transport_checksum_constructor_quicchannel_connect_obfuscated() != 54678) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureConstructTransportInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all