//
//  QuicSuppressionLedger.swift
//  Construct Messenger
//
//  What the device learned about QUIC on a network, kept per network instead of one slot.
//
//  The suppression ladder is cleared on every network path change, and that is correct — the new
//  network may not block QUIC even if the old one did, so we re-probe when you move rather than
//  when you relaunch (`resetDegradedModeOnNetworkChange`). But clearing it also wiped the single
//  persisted record, which was tagged with a network identity. So the record only ever described
//  the network you were on *right now*, and stepping off a network erased what you had learned
//  about it.
//
//  Device, 2026-08-11, one phone moving between Wi-Fi and cellular:
//
//      06:27:34  Fast-UDP open failure #1/1 [accept_timeout] (network rung 1)
//      06:27:34  Fast-UDP (QUIC/H3) suppressed 3600s on this network — using H2 (rung 2)
//      06:31:44  Network reachability changed: ONLINE (wifi)
//      06:31:48  Network reachability changed: ONLINE (cellular)      ← ladder cleared
//      06:38:02  Network reachability changed: ONLINE (wifi)          ← back where we started
//      06:38:35  Fast-UDP open failure #1/2 [stream_failure] (network rung 0)   ← rung 0 again
//      06:38:44  Fast-UDP open failure #2/2 [stream_failure] (network rung 0)
//      06:38:44  Fast-UDP (QUIC/H3) suppressed 300s on this network — using H2 (rung 1)
//
//  Eleven minutes after concluding this Wi-Fi was worth an hour of suppression, the device came
//  back to it and started from zero — two failed opens, a ~3s handshake timeout each, and a stream
//  that churned through two more open timeouts before settling. On a phone, which changes network
//  several times an hour, the ladder can therefore never accumulate: every return to a
//  QUIC-hostile network pays full price again. The one-shot `didRestoreQuicSuppression` restore
//  does not help — it runs once per launch, and these switches happen mid-session.
//
//  # Storing which networks you have been on
//
//  A list of network fingerprints at rest is movement history, which is not something a
//  privacy-first messenger should leave lying in UserDefaults just to remember a transport
//  preference. We only ever need equality, never the value, so entries are keyed by
//  `SHA256(per-install salt ‖ identity)`. Someone reading the container learns how many networks
//  the device has an opinion about, not which. The list is bounded and the salt is regenerated by
//  a local reset along with everything else.
//

import Foundation
import CryptoKit

enum QuicSuppressionLedger {

    /// What we know about one network. `updatedAt` exists only to decide what to evict.
    struct Record: Codable, Equatable {
        var strikes: Int
        var suppressedUntil: Date?
        var updatedAt: Date
    }

    /// Bounded on purpose: enough for home / work / phone / a couple of visited networks, few
    /// enough that the file is not a travel diary. Eviction is least-recently-updated.
    static let maxNetworks = 8

    // MARK: - The decisions (pure — no storage, no clock, no network)

    /// What the in-memory ladder should become on arriving at `network`.
    ///
    /// An unknown network yields rung 0 with no window: a network we have never judged must be
    /// probed, which is the behaviour the network-change reset was written to guarantee and must
    /// keep. A known one yields what it taught us, with an expired window dropped but its rung
    /// kept — the same split the single-slot restore made, for the same reason: the window says
    /// "don't try yet", the rung says "how badly this went last time".
    static func stateOnArrival(
        at network: String,
        store: [String: Record],
        now: Date
    ) -> (strikes: Int, suppressedUntil: Date?) {
        guard !network.isEmpty, let record = store[network] else { return (0, nil) }
        guard let until = record.suppressedUntil, until > now else { return (record.strikes, nil) }
        return (record.strikes, until)
    }

    /// The store after recording what we just learned about `network`.
    ///
    /// Returning a new dictionary rather than mutating one keeps this testable without a
    /// UserDefaults double, and the eviction rule — the thing that can silently lose the entry you
    /// care about — visible in one expression.
    static func remembering(
        _ store: [String: Record],
        network: String,
        strikes: Int,
        suppressedUntil: Date?,
        now: Date
    ) -> [String: Record] {
        guard !network.isEmpty else { return store }
        var updated = store

        // Nothing learned is nothing stored: a network QUIC works on should not occupy a slot that
        // a network QUIC fails on could use.
        if strikes == 0, suppressedUntil == nil {
            updated.removeValue(forKey: network)
            return updated
        }

        updated[network] = Record(strikes: strikes, suppressedUntil: suppressedUntil, updatedAt: now)
        guard updated.count > maxNetworks else { return updated }

        // Evict least-recently-updated, never the entry we just wrote.
        let evictable = updated
            .filter { $0.key != network }
            .sorted { $0.value.updatedAt < $1.value.updatedAt }
        for (key, _) in evictable.prefix(updated.count - maxNetworks) {
            updated.removeValue(forKey: key)
        }
        return updated
    }

    // MARK: - Keying

    /// Stable, non-reversible key for a network identity.
    ///
    /// Equality is all the ladder needs, so the identity itself is never written down. The salt is
    /// per install, which is what stops the stored digests from being checked against a list of
    /// known SSIDs/gateways by anyone who gets the container.
    static func key(for identity: String, salt: Data) -> String {
        guard !identity.isEmpty else { return "" }
        var hasher = SHA256()
        hasher.update(data: salt)
        hasher.update(data: Data(identity.utf8))
        return hasher.finalize().compactMap { String(format: "%02x", $0) }.joined()
    }
}
